M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 12:21:34 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T12:21:34-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.6Y-2.5
X5.6Y-2.8
X5.7Y-3.1
X5.8Y-2.9
X5.8Y-2.9414
X5.9Y-2.7
X5.9Y-3.1
X6.2Y-2.9
X6.2Y-3.0
X6.3Y-2.9
T2
X5.7949Y-2.4
X5.9949Y-2.4
T0
M30
